import { blockRegistry } from "./block-registry";
import { basicBlocks } from "./blocks/basic-blocks";
import { columnBlocks } from "./blocks/column-blocks";
import { aboutBlocks } from "./blocks/about-blocks";
import { missionVisionBlocks } from "./blocks/mission-vision-blocks";
import { initializeProductCardsBlock } from "./blocks/product-cards-blocks";
import { dualCardBlocks } from "./blocks/dual-card-blocks";
import { ctaBlocks } from "./blocks/cta-blocks";
import { documentDownloadBlocks, initializeDocumentDownloadBlocks } from "./blocks/document-download-blocks";
import { initializeSavingsSectionBlock } from "./blocks/savings-carousel-blocks";
import { productLinkCardsBlocks } from "./blocks/product-link-cards-blocks";
import { iconLinksBlocks } from "./blocks/icon-links-blocks";
import { iconCardsBlocks } from "./blocks/icon-cards-blocks";
import { assistanceCardsBlocks } from "./blocks/assistance-cards-blocks";
import { promoCtaBlocks } from "./blocks/promo-cta-blocks";
import { featureBlocks } from "./blocks/feature-blocks";
import { tabsBlocks, initializeTabsBlocks } from "./blocks/tabs-blocks";
import { splitContentBlocks } from "./blocks/split-content-blocks";
import { statsStripBlocks } from "./blocks/stats-strip-blocks";
import { serviceCardsBlocks } from "./blocks/service-cards-blocks";
import { contactInfoBlocks } from "./blocks/contact-info-blocks";
import { richListBlocks } from "./blocks/rich-list-blocks";
import { productDetailBlocks } from "./blocks/product-detail-blocks";
import { financingBlocks } from "./blocks/financing-blocks";
import { newsGridBlocks } from "./blocks/news-grid-blocks";
import { barChartBlocks, initializeBarChartBlocks } from "./blocks/bar-chart-blocks";
import { formBlocks } from "./blocks/form-blocks";
import { tableBlocks, initializeTableBlocks } from "./blocks/table-blocks";
import { buttonBlocks, initializeButtonBlocks } from "./blocks/button-blocks";
import { badgeBlocks } from "./blocks/badge-blocks";
import { mapFilterBlocks, initializeMapFilterBlocks } from "./blocks/map-filter-blocks";
import { bannerBlocks, initializeBannerBlocks } from "./blocks/banner-blocks";
import { assetsBlocks, initializeAssetsBlocks } from "@/editor/blocks/assets-blocks";
import { initializeHeroBannerBlock } from "@/editor/blocks/hero-banner-blocks";

export function addCustomBlocks(editor) {
    blockRegistry.registerBlocks(basicBlocks);
    blockRegistry.registerBlocks(columnBlocks);
    blockRegistry.registerBlocks(bannerBlocks);
    blockRegistry.registerBlocks(statsStripBlocks);
    blockRegistry.registerBlocks(tabsBlocks);
    blockRegistry.registerBlocks(aboutBlocks);
    blockRegistry.registerBlocks(missionVisionBlocks);
    blockRegistry.registerBlocks(productLinkCardsBlocks);
    blockRegistry.registerBlocks(iconLinksBlocks);
    blockRegistry.registerBlocks(iconCardsBlocks);
    blockRegistry.registerBlocks(assistanceCardsBlocks);
    blockRegistry.registerBlocks(dualCardBlocks)
    blockRegistry.registerBlocks(splitContentBlocks);
    blockRegistry.registerBlocks(productDetailBlocks);
    blockRegistry.registerBlocks(ctaBlocks);
    blockRegistry.registerBlocks(documentDownloadBlocks);
    blockRegistry.registerBlocks(promoCtaBlocks);
    blockRegistry.registerBlocks(featureBlocks);
    blockRegistry.registerBlocks(serviceCardsBlocks);
    blockRegistry.registerBlocks(contactInfoBlocks);
    blockRegistry.registerBlocks(richListBlocks);
    blockRegistry.registerBlocks(newsGridBlocks);
    blockRegistry.registerBlocks(barChartBlocks);
    blockRegistry.registerBlocks(formBlocks);
    blockRegistry.registerBlocks(tableBlocks);
    blockRegistry.registerBlocks(buttonBlocks);
    blockRegistry.registerBlocks(badgeBlocks);
    blockRegistry.registerBlocks(financingBlocks);
    blockRegistry.registerBlocks(mapFilterBlocks);
    blockRegistry.registerBlocks(assetsBlocks);
    blockRegistry.applyToEditor(editor);

    initializeMapFilterBlocks(editor);
    initializeBannerBlocks(editor);
    initializeHeroBannerBlock(editor);
    initializeSavingsSectionBlock(editor);
    initializeProductCardsBlock(editor);
    initializeButtonBlocks(editor);
    initializeTabsBlocks(editor);
    initializeBarChartBlocks(editor);
    initializeTableBlocks(editor);
    initializeDocumentDownloadBlocks(editor);
    initializeAssetsBlocks(editor);
}
